# name: Build and Deploy Documentation

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 19

#       - name: Install dependencies
#         run: npm install

#       - name: Build documentation
#         run: npm run build

#       - name: Deploy to GitHub Pages
#         run: |
#           git config user.name "${{ github.actor }}"
#           git config user.email "${{ github.actor }}@users.noreply.github.com"
#           npm run deploy
#         env:
#           CI: true
#         if: success()

